### ISSUE TITLE
Can we have a second option of champion pick in case of ban of the main one?

### ISSUE THREAD

**Issue by iSte94** [devRael1/LolyTools#5]
Hello, is it possible as the title?

**Comment by devRael1** [comment]
Hello,
I don't know if it's possible. I need to analyze this.

**Comment by xunyangjian1** [comment]
Can skills be automatically upgraded? I really need it. Thank you

**Comment by devRael1** [comment]
> Can skills be automatically upgraded? I really need it. Thank you

I don't understand this question.
Can you be more explicit please ?

**Comment by devRael1** [comment]
zdzd
